server:
  port: 8081
spring:
  application:
    name: library
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_management?useSSL=false&serverTimezone=UTC
    username: "root"
    password: "6446530"
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
  type-aliases-package: com.example.librarydemo.entity # ?????
logging:
  level:
    com.example.librarydemo: debug
